# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
plugins: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               NEC's House
tagline:             'hack ur life'
description:         'Geek | Crack'
url:                 https://nec2017.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Nancy thE Cat
  url:               https://weibo.com/u/5758919434
  email:             chinano1cnm@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/nec2017
twitter:			http://twitter.com/nec666
disqus:             test

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu

theme: jekyll-theme-hacker